config/routes.rb
Rails.application.routes.draw do

  resources :users
  resources :trips
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/trip.rb
class Trip < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_many :trips
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
    before_action :set_trip, only: [:show, :edit, :update, :destroy]

  def index
    @trips = Trip.all
  end

  def show
  end

  def new
    @trip = Trip.new
  end

  def create
    @trip = Trip.new(trip_params)
    if @trip.save
      redirect_to trips_path, notice: 'Voyage créé avec succès.'
    else
      render :new
    end
  end  

  def edit
  end

  def update
    if @trip.update(trip_params)
      redirect_to @trip, notice: 'Voyage mis à jour avec succès.', format: :html
    else
      render :edit
    end
  end

  def destroy
    @trip.destroy
    redirect_to trips_url, notice: 'Voyage supprimé avec succès.'
  end

  private

  def set_trip
    @trip = Trip.find(params[:id])
  end

  def trip_params
    params.require(:trip).permit(:user_id, :destination, :description, :date_debut, :date_fin)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user, notice: 'Utilisateur créé avec succès.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'Utilisateur mis à jour avec succès.'
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_url, notice: 'Utilisateur supprimé avec succès.'
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:nom, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LeCarnetDesVoyages</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/trips/_form.html.erb
<div class='form-user'>
<%= form_with(model: @trip, local: true) do |form| %>
    <% if @trip.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@trip.errors.count, 'erreur') %> interdit cette création :</h2>
  
        <ul>
          <% @trip.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :user_id, "Utilisateur" %>
    <%= form.collection_select :user_id, User.all, :id, :nom, prompt: "Sélectionnez un utilisateur" %>
    </div>
  
    <div class="field">
      <%= form.label :destination %>
      <%= form.text_field :destination %>
    </div>
  
    <div class="field">
      <%= form.label :description %>
      <%= form.text_area :description %>
    </div>
  
    <div class="field">
      <%= form.label :date_debut %>
      <%= form.date_field :date_debut %>
    </div>
  
    <div class="field">
      <%= form.label :date_fin %>
      <%= form.date_field :date_fin %>
    </div>
  
    <div class="actions">
      <%= form.submit @trip.new_record? ? 'Créer le voyage' : 'Mettre à jour le voyage', class: 'btn btn-primary' %>
      <%= link_to 'Annuler', users_path, class: 'btn btn-danger' %>
    </div>
  <% end %>
  </div>

app/views/trips/edit.html.erb
<h1>Modifier Voyage</h1>

<%= render 'form' %>

app/views/trips/index.html.erb
<h1>Liste des Voyages</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Nom</th>
      <th>Utilisateur</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @trips.each do |trip| %>
      <tr>
        <td class='td-trip'><%= trip.id %></td>
        <td class='td-trip'><%= trip.destination %></td>
        <td class='td-trip'><%= "#{trip.user.nom} (ID : #{trip.user.id})" if trip.user %></td>
        <td class='td-trip'>
          <%= link_to 'Voir', trip_path(trip), class: 'btn btn-primary' %>
          <%= button_to "Supprimer", { controller: :trips, action: 'destroy', id: trip.id }, method: :delete, data: { confirm: 'Êtes-vous sûr?' }, class: 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="new-user">
<%= link_to 'Nouveau voyage', new_trip_path, class: 'btn btn-success' %>
</div>

app/views/trips/new.html.erb
<h1>Nouveau Voyage</h1>

<%= render 'form' %>

app/views/trips/show.html.erb
<h1>Voyage : <%= @trip.destination %></h1>
<p>Description: <%= @trip.description %></p>
<p>Date de début: <%= l(@trip.date_debut, format: :long) %></p>
<p>Date de fin: <%= l(@trip.date_fin, format: :long) %></p>
<p>Utilisateur: <%= link_to @trip.user.nom, @trip.user %></p>

<div class='btn-user'>
<%= link_to 'Modifier', edit_trip_path(@trip), class: 'btn btn-primary' %>
<%= button_to "Supprimer", { controller: :trips, action: 'destroy', id: @trip.id }, method: :delete, data: { confirm: 'Êtes-vous sûr?' }, class: 'btn btn-danger' %>
</div>
<%= link_to 'liste des voyages', trips_path, class: 'btn btn-primary' %>

app/views/users/_form.html.erb
<div class='form-user'>
<%= form_with(model: @user, local: true) do |form| %>
    <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, 'erreur') %> interdit cette création :</h2>
  
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :nom %>
      <%= form.text_field :nom %>
    </div>
  
    <div class="field">
      <%= form.label :email %>
      <%= form.email_field :email %>
    </div>
  
    <div class="actions">
      <%= form.submit @user.new_record? ? 'Créer l\'utilisateur' : 'Mettre à jour l\'utilisateur', class: 'btn btn-primary' %>
      <%= link_to 'Annuler', users_path, class: 'btn btn-danger' %>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1>Modifier Utilisateur</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1>Liste des Utilisateurs</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Nom</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td class='td-user'><%= user.id %></td>
        <td class='td-user'><%= user.nom %></td>
        <td class='td-user'>
          <%= link_to 'Voir', user_path(user), class: 'btn btn-primary' %>
          <%= button_to "Supprimer", { controller: :users, action: 'destroy', id: user.id }, method: :delete, data: { confirm: 'Êtes-vous sûr?' }, class: 'btn btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<div class="new-user">
<%= link_to 'Nouvel Utilisateur', new_user_path, class: 'btn btn-success' %>
</div>

app/views/users/new.html.erb
<h1>Nouvel Utilisateur</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1>Utilisateur: <%= @user.nom %></h1>
<p>ID: <%= @user.id %></p>
<p>Nom: <%= @user.nom %></p>
<p>Email: <%= @user.email %></p>
<br>
<h2>Voyages associés :</h2>
<ul>
  <% @user.trips.each do |trip| %>
    <li>
      <%= link_to trip.destination, trip %>
    </li>
  <% end %>
</ul>

<div class='btn-user'>
<%= link_to 'Modifier', edit_user_path(@user), class: 'btn btn-primary' %>
<%= button_to "Supprimer", { controller: :users, action: 'destroy', id: @user.id }, method: :delete, data: { confirm: 'Êtes-vous sûr?' }, class: 'btn btn-danger' %>
</div>
<%= link_to 'liste des utilisateurs', users_path, class: 'btn btn-primary' %>